### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ghost** [segator/PlexRemoteTranscoderDocker#1]
Is this GIT connected to this:https://github.com/wnielson/Plex-Remote-Transcoder   ? If so it would be a good ide to meantion this at your page

**Comment by segator** [comment]
No, it's connected with https://github.com/segator/PlexRemoteTranscoderOrchestrator but I inspired by wnielson, the idea is from him :) I Only develop it, but it's not finished yet I'm still developing.

**Comment by ghost** [comment]
Ok the name of the project was so simalry. That was the reason for my question
